export interface Curriculum {
    idDatosPersonales?: number;
    idUsuario?: number;
    IdPlantillaAplicada?: number;
    dicCiudadResidencia?: number;
    dicDepartamento?: number;
    dicTipoDocumento?: number;
    dicProfesion?: number;
    dicAreaTrabajo? :number;
    dicAspiracionSalarial? :number;
    nombres? :string;
    apellidoPaterno? :string;
    apellidoMaterno? :string;
    rutaFoto? :string;
    identificacion?: string;
    correoElectronico?: string;
    telefonoCelular? :string;
    direccionResidencia? :string;
    anosExperiencia? :string;
    paisesTrabajar? :string;
    redesSociales? :string;
    descripcionPerfilProfesional? :string;
    genero? :string;
    movilidadLaboral? :string;
    idiomaNivel? :string;
    habilidades? :string;
    fechaNacimiento? :string;
    fechaCreacion? :Date;
    fechaActualizacion? :Date;
    vigente?: boolean;
    tipoTextoHV? :string;
    colorHV? :string;
}
export interface plantillaHTML{
    estadoPlantilla?: number;
    fechaActualizacion?: Date;
    fechaCreacion?: Date;
    htmlPlantilla?: string;
    idPlantilla?: number;
    nombrePlantilla?: number;
    tagEstudiosComplementarios?: string;
    tagEstudiosPrincipales?: string;
    tagExperienciaLaboral?: string;
    tagFuncionesLogros?: string;
    tagIdioma?: string;
    tagMovilidadLaboral?: string;
    tagRedes?: string;
    vigente?: boolean;
}